# Dockerfile for katana tool
FROM alpine:3.18
RUN apk add --no-cache curl
ARG KATANA_VERSION=v1.4.0
ARG KATANA_URL="https://github.com/projectdiscovery/katana/releases/download/${KATANA_VERSION}/katana_${KATANA_VERSION#v}_linux_amd64.zip"
WORKDIR /tmp
RUN curl -sSL -o katana.zip "$KATANA_URL" \
	&& unzip katana.zip \
	&& mv katana /usr/local/bin/katana \
	&& chmod +x /usr/local/bin/katana \
	&& rm -rf katana.zip LICENSE README.md
