FROM golang:1.21 as builder
RUN git clone https://github.com/jaeles-project/gospider.git /gospider
WORKDIR /gospider
RUN go build -o /usr/local/bin/gospider .

FROM debian:stable-slim
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/local/bin/gospider /usr/local/bin/gospider
ENTRYPOINT ["/usr/local/bin/gospider"]